
-- Table for doctor invite codes generated by admin
CREATE TABLE public.doctor_invite_codes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  created_by uuid NOT NULL,
  used_by uuid,
  used_at timestamp with time zone,
  is_used boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone
);

ALTER TABLE public.doctor_invite_codes ENABLE ROW LEVEL SECURITY;

-- Only admins can create/view/manage invite codes
CREATE POLICY "Admins can do everything with invite codes"
  ON public.doctor_invite_codes FOR ALL
  USING (is_admin())
  WITH CHECK (is_admin());

-- Anyone authenticated can read a specific code to validate it (but only unused ones)
CREATE POLICY "Anyone can validate unused codes"
  ON public.doctor_invite_codes FOR SELECT
  TO authenticated
  USING (is_used = false);

-- Allow authenticated users to update a code (mark as used) when registering
CREATE POLICY "Authenticated users can use a code"
  ON public.doctor_invite_codes FOR UPDATE
  TO authenticated
  USING (is_used = false AND code IS NOT NULL)
  WITH CHECK (is_used = true AND used_by = auth.uid());
