-- SECURITY FIX Part 2: Tables E-P

ALTER POLICY "Patients can view own exam reports" ON public.exam_reports TO authenticated;
ALTER POLICY "Patients can view own exam requests" ON public.exam_requests TO authenticated;
ALTER POLICY "Patients manage own favorites" ON public.favorite_doctors TO authenticated;
ALTER POLICY "Admins can view all guest patients" ON public.guest_patients TO authenticated;
ALTER POLICY "Patient manages own metrics" ON public.health_metrics TO authenticated;
ALTER POLICY "Admins manage tips" ON public.health_tips TO authenticated;
ALTER POLICY "Admins can view all access logs" ON public.medical_record_access_logs TO authenticated;
ALTER POLICY "Doctors can view logs for their patients" ON public.medical_record_access_logs TO authenticated;
ALTER POLICY "Users can insert access logs" ON public.medical_record_access_logs TO authenticated;
ALTER POLICY "Patients can view own records" ON public.medical_records TO authenticated;
ALTER POLICY "Participants can send messages" ON public.messages TO authenticated;
ALTER POLICY "Participants can view messages" ON public.messages TO authenticated;
ALTER POLICY "Users can mark messages as read" ON public.messages TO authenticated;
ALTER POLICY "Admins can view subscribers" ON public.newsletter_subscribers TO authenticated;
ALTER POLICY "Authenticated or service can insert notifications" ON public.notifications TO authenticated;
ALTER POLICY "Users can delete own notifications" ON public.notifications TO authenticated;
ALTER POLICY "Users can update own notifications" ON public.notifications TO authenticated;
ALTER POLICY "Users can view own notifications" ON public.notifications TO authenticated;
ALTER POLICY "Doctors can update queue" ON public.on_demand_queue TO authenticated;
ALTER POLICY "Doctors view assigned to them" ON public.on_demand_queue TO authenticated;
ALTER POLICY "Doctors view waiting queue" ON public.on_demand_queue TO authenticated;
ALTER POLICY "Patients can insert queue entry" ON public.on_demand_queue TO authenticated;
ALTER POLICY "Patients view own queue entries" ON public.on_demand_queue TO authenticated;
ALTER POLICY "Partners can insert own profile" ON public.partner_profiles TO authenticated;
ALTER POLICY "Partners can update own profile" ON public.partner_profiles TO authenticated;
ALTER POLICY "Partners can view own profile" ON public.partner_profiles TO authenticated;
ALTER POLICY "Parties can view consent" ON public.patient_consents TO authenticated;
ALTER POLICY "Patients can create own consent" ON public.patient_consents TO authenticated;
ALTER POLICY "Patients can view own documents" ON public.patient_documents TO authenticated;
ALTER POLICY "Users can delete own documents" ON public.patient_documents TO authenticated;
ALTER POLICY "Users can upload documents" ON public.patient_documents TO authenticated;
ALTER POLICY "Only admins can manage plans" ON public.plans TO authenticated;
ALTER POLICY "Doctors can view patient symptoms" ON public.pre_consultation_symptoms TO authenticated;
ALTER POLICY "Patients can insert own symptoms" ON public.pre_consultation_symptoms TO authenticated;
ALTER POLICY "Patients can view own symptoms" ON public.pre_consultation_symptoms TO authenticated;
ALTER POLICY "Admins manage all renewals" ON public.prescription_renewals TO authenticated;
ALTER POLICY "Doctors update renewals" ON public.prescription_renewals TO authenticated;
ALTER POLICY "Doctors view own assigned renewals" ON public.prescription_renewals TO authenticated;
ALTER POLICY "Doctors view pending/assigned renewals" ON public.prescription_renewals TO authenticated;
ALTER POLICY "Patients insert own renewals" ON public.prescription_renewals TO authenticated;
ALTER POLICY "Patients manage own renewals" ON public.prescription_renewals TO authenticated;
ALTER POLICY "Partners and admins can view validations" ON public.prescription_validations TO authenticated;
ALTER POLICY "Partners can create validations" ON public.prescription_validations TO authenticated;
ALTER POLICY "Users can update own profile" ON public.profiles TO authenticated;
ALTER POLICY "Users can manage own push subs" ON public.push_subscriptions TO authenticated;